version: '3.8'

services:
  # 1. PostgreSQL Database Server
  postgres_db:
    image: postgres:15-alpine
    container_name: expense_tracker_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # Store data on a host machine.
    networks:
      - expense_network

  # 2. pgAdmin (UI tool for database management)
  pgadmin:
    image: dpage/pgadmin4
    container_name: expense_tracker_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80" # Access pgAdmin via localhost:5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres_db
    networks:
      - expense_network

  # 3. Spring Boot Backend
  backend:
    build: .
    container_name: expense_tracker_backend
    ports:
      - "8080:8080" # Open the port for the frontend to call the API.
    depends_on:
      - postgres_db # Make the backend wait for the database to wake up before running.
    networks:
      - expense_network # Allow Backend to connect to DB
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}

# Declare Volumes to ensure data is not lost when deleting the container.
volumes:
  pgdata:
  pgadmin_data:

# Declare a Network so that containers can call each other.
networks:
  expense_network:
    driver: bridge